# ==============================================================
# Root Orchestration
# ==============================================================

resource "azurerm_resource_group" "main" {
  name     = local.resource_names.resource_group
  location = var.primary_region
  tags     = local.common_tags
}

# --------------------------------------------------------------
# Monitoring (deployed first — other modules depend on it)
# --------------------------------------------------------------

module "monitoring" {
  source = "./modules/monitoring"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  log_analytics_name  = local.resource_names.log_analytics
  app_insights_name   = local.resource_names.app_insights
  retention_days      = var.log_retention_days
  tags                = local.common_tags
}

# --------------------------------------------------------------
# Networking
# --------------------------------------------------------------

module "networking" {
  source = "./modules/networking"

  resource_group_name   = azurerm_resource_group.main.name
  location              = azurerm_resource_group.main.location
  vnet_name             = local.resource_names.vnet
  address_space         = var.vnet_address_space
  subnet_cidrs          = var.subnet_cidrs
  container_subnet_name = local.resource_names.container_subnet
  db_subnet_name        = local.resource_names.db_subnet
  private_subnet_name   = local.resource_names.private_subnet
  container_nsg_name    = local.resource_names.container_nsg
  db_nsg_name           = local.resource_names.db_nsg
  tags                  = local.common_tags
}

# --------------------------------------------------------------
# Private DNS Zone (for PostgreSQL private access)
# --------------------------------------------------------------

resource "azurerm_private_dns_zone" "postgres" {
  name                = local.resource_names.private_dns_zone
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.common_tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "postgres" {
  name                  = "${local.name_prefix}-pg-dns-link"
  private_dns_zone_name = azurerm_private_dns_zone.postgres.name
  resource_group_name   = azurerm_resource_group.main.name
  virtual_network_id    = module.networking.vnet_id
  registration_enabled  = false
  tags                  = local.common_tags
}

# --------------------------------------------------------------
# PostgreSQL
# --------------------------------------------------------------

module "postgres" {
  source = "./modules/postgres"

  resource_group_name   = azurerm_resource_group.main.name
  location              = azurerm_resource_group.main.location
  server_name           = local.resource_names.postgres
  database_name         = var.project_name
  admin_username        = var.db_admin_username
  sku_name              = var.db_sku_name
  storage_mb            = var.db_storage_mb
  postgres_version      = var.db_version
  backup_retention_days = var.db_backup_retention_days
  geo_redundant_backup  = var.db_geo_redundant_backup
  high_availability     = var.db_high_availability
  delegated_subnet_id   = module.networking.db_subnet_id
  private_dns_zone_id   = azurerm_private_dns_zone.postgres.id
  tags                  = local.common_tags

  depends_on = [azurerm_private_dns_zone_virtual_network_link.postgres]
}

# FIX 1 — Allow pgvector extension on the Azure PG Flexible Server.
# Without this, CREATE EXTENSION vector fails on startup auto-migrate.
resource "azurerm_postgresql_flexible_server_configuration" "pgvector" {
  name      = "azure.extensions"
  server_id = module.postgres.server_id
  value     = "VECTOR"
}

# --------------------------------------------------------------
# Redis Cache (Basic C0 — cache-only, no VNet integration at this tier)
# --------------------------------------------------------------

resource "azurerm_redis_cache" "main" {
  name                = local.resource_names.redis
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  capacity            = 0
  family              = "C"
  sku_name            = "Basic"
  minimum_tls_version = "1.2"
  tags                = local.common_tags
}

# --------------------------------------------------------------
# Azure Blob Storage (media: profile photos, tile media, voice notes)
# All containers are private — access via SAS tokens generated by the backend.
# --------------------------------------------------------------

resource "azurerm_storage_account" "woven_media" {
  name                            = local.resource_names.storage_account
  resource_group_name             = azurerm_resource_group.main.name
  location                        = azurerm_resource_group.main.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
  tags                            = local.common_tags
}

resource "azurerm_storage_container" "profile_photos" {
  name                  = "profile-photos"
  storage_account_name  = azurerm_storage_account.woven_media.name
  container_access_type = "private"
}

resource "azurerm_storage_container" "tile_media" {
  name                  = "tile-media"
  storage_account_name  = azurerm_storage_account.woven_media.name
  container_access_type = "private"
}

resource "azurerm_storage_container" "voice_notes" {
  name                  = "voice-notes"
  storage_account_name  = azurerm_storage_account.woven_media.name
  container_access_type = "private"
}

# --------------------------------------------------------------
# Azure Container Registry
# --------------------------------------------------------------

module "acr" {
  source = "./modules/acr"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  acr_name            = local.resource_names.acr
  sku                 = var.acr_sku
  tags                = local.common_tags
}

# --------------------------------------------------------------
# Container Apps Environment
# --------------------------------------------------------------

module "container_apps" {
  source = "./modules/container_apps"

  resource_group_name            = azurerm_resource_group.main.name
  location                       = azurerm_resource_group.main.location
  environment_name               = local.resource_names.container_env
  log_analytics_workspace_id     = module.monitoring.log_analytics_workspace_id
  subnet_id                      = module.networking.container_subnet_id
  internal_only                  = var.container_apps_internal_only
  backend_app_name               = local.resource_names.backend_app
  frontend_app_name              = local.resource_names.frontend_app
  acr_login_server               = module.acr.login_server
  acr_id                         = module.acr.acr_id
  postgres_connection_string     = module.postgres.connection_string
  app_insights_connection_string = module.monitoring.app_insights_connection_string
  redis_connection_string        = "${azurerm_redis_cache.main.hostname}:${azurerm_redis_cache.main.ssl_port},password=${azurerm_redis_cache.main.primary_access_key},ssl=True,abortConnect=False"
  storage_connection_string      = azurerm_storage_account.woven_media.primary_connection_string
  backend_image_tag              = var.backend_image_tag
  frontend_image_tag             = var.frontend_image_tag
  custom_domain                  = var.custom_domain
  google_client_id               = var.google_client_id
  encryption_master_key          = var.encryption_master_key
  replicate_api_token            = var.replicate_api_token
  openai_api_key                 = var.openai_api_key
  google_places_api_key          = var.google_places_api_key
  tags                           = local.common_tags
}
