// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WovenBackend.Data;

#nullable disable

namespace WovenBackend.Migrations
{
    [DbContext(typeof(WovenDbContext))]
    [Migration("20260104003554_AddMatchmakingEngine")]
    partial class AddMatchmakingEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean")
                        .HasColumnName("blocked");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<bool>("ChatStarted")
                        .HasColumnType("boolean")
                        .HasColumnName("chat_started");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean")
                        .HasColumnName("expired");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Messages24h")
                        .HasColumnType("integer")
                        .HasColumnName("messages_24h");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<bool>("Unmatched")
                        .HasColumnType("boolean")
                        .HasColumnName("unmatched");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "CandidateId", "DateUtc");

                    b.ToTable("match_outcomes");
                });

            modelBuilder.Entity("WovenBackend.Data.AuthIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("AuthIdentities");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.DailyDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DateUtc")
                        .IsUnique();

                    b.ToTable("DailyDecks");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.MatchExplanation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BulletsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CandidateId", "DateUtc");

                    b.ToTable("MatchExplanations");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserDynamicIntakeSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CycleEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CycleStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenerationMetaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MappingVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VariantJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VariantSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CycleId")
                        .IsUnique();

                    b.ToTable("UserDynamicIntakeSets");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserFoundationalQuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeferredUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationMetaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionsHash")
                        .HasColumnType("text");

                    b.Property<string>("QuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionsSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"AnsweredAt\" IS NULL");

                    b.HasIndex("UserId", "Version")
                        .IsUnique();

                    b.ToTable("UserFoundationalQuestionSets");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserVector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PillarScoresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VectorJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Version")
                        .IsUnique();

                    b.ToTable("UserVectors");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserVectorTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Tag", "TagType");

                    b.HasIndex("UserId", "Version", "TagType");

                    b.ToTable("UserVectorTags");
                });

            modelBuilder.Entity("WovenBackend.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text");

                    b.Property<string>("ProfileStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WovenBackend.Data.UserFoundationalV1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserFoundationalV1s");
                });

            modelBuilder.Entity("WovenBackend.Data.UserIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpennessJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryIntent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReflectionSentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserIntents");
                });

            modelBuilder.Entity("WovenBackend.Data.UserOptionalField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("UserOptionalFields");
                });

            modelBuilder.Entity("WovenBackend.Data.UserPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("WovenBackend.Data.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(99);

                    b.Property<int>("AgeMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(18);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistanceMiles")
                        .HasColumnType("integer");

                    b.Property<string>("InterestedInJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelationshipStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("WovenBackend.Data.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("WovenBackend.Data.UserWeeklyVibe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserWeeklyVibes");
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.Block", b =>
                {
                    b.Property<int>("BlockerId")
                        .HasColumnType("integer")
                        .HasColumnName("blocker_id");

                    b.Property<int>("BlockedId")
                        .HasColumnType("integer")
                        .HasColumnName("blocked_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("BlockerId", "BlockedId");

                    b.HasIndex("BlockedId");

                    b.HasIndex("BlockerId");

                    b.ToTable("blocks", t =>
                        {
                            t.HasCheckConstraint("ck_blocks_no_self", "\"blocker_id\" <> \"blocked_id\"");
                        });
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_user_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ThreadId");

                    b.ToTable("chat_messages", t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_body_len", "length(\"body\") >= 1 AND length(\"body\") <= 1000");
                        });
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.ChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("chat_threads");
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.DailyInteraction", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<short>("PendingUsed")
                        .HasColumnType("smallint")
                        .HasColumnName("pending_used");

                    b.Property<short>("TotalUsed")
                        .HasColumnType("smallint")
                        .HasColumnName("total_used");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "DateUtc");

                    b.ToTable("daily_interactions", t =>
                        {
                            t.HasCheckConstraint("ck_daily_pending_cap", "\"pending_used\" >= 0 AND \"pending_used\" <= 2");

                            t.HasCheckConstraint("ck_daily_pending_le_total", "\"pending_used\" <= \"total_used\"");

                            t.HasCheckConstraint("ck_daily_total_cap", "\"total_used\" >= 0 AND \"total_used\" <= 5");
                        });
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BalloonState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("balloon_state");

                    b.Property<DateTimeOffset?>("BothMessagedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("both_messaged_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedReason")
                        .HasColumnType("text")
                        .HasColumnName("closed_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EdgeOwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("edge_owner_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FindLoveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("find_love_at");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("match_type");

                    b.Property<int>("UserAId")
                        .HasColumnType("integer")
                        .HasColumnName("user_a_id");

                    b.Property<int>("UserBId")
                        .HasColumnType("integer")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id");

                    b.HasIndex("EdgeOwnerId");

                    b.HasIndex("BalloonState", "ExpiresAt");

                    b.HasIndex("UserAId", "BalloonState", "ExpiresAt");

                    b.HasIndex("UserAId", "UserBId", "BalloonState")
                        .IsUnique()
                        .HasFilter("\"balloon_state\" = 'ACTIVE'");

                    b.HasIndex("UserBId", "BalloonState", "ExpiresAt");

                    b.ToTable("matches", t =>
                        {
                            t.HasCheckConstraint("ck_matches_expires_after_created", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_matches_no_self", "\"user_a_id\" <> \"user_b_id\"");

                            t.HasCheckConstraint("ck_matches_state_closed_fields", "\r\n                (\r\n                  \"balloon_state\" = 'ACTIVE' AND\r\n                  \"closed_reason\" IS NULL AND\r\n                  \"closed_at\" IS NULL\r\n                )\r\n                OR\r\n                (\r\n                  \"balloon_state\" = 'CLOSED' AND\r\n                  \"closed_reason\" IS NOT NULL AND\r\n                  \"closed_at\" IS NOT NULL\r\n                )\r\n                ");

                            t.HasCheckConstraint("ck_matches_type_edge_owner", "\r\n                (\r\n                  \"match_type\" = 'PURE' AND\r\n                  \"edge_owner_id\" IS NULL\r\n                )\r\n                OR\r\n                (\r\n                  \"match_type\" = 'EDGE' AND\r\n                  \"edge_owner_id\" IS NOT NULL\r\n                )\r\n                ");
                        });
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.MomentResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choice");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<int>("FromUserId")
                        .HasColumnType("integer")
                        .HasColumnName("from_user_id");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("DateUtc", "FromUserId", "ToUserId")
                        .IsUnique();

                    b.ToTable("moment_responses", t =>
                        {
                            t.HasCheckConstraint("ck_moment_responses_no_self", "\"from_user_id\" <> \"to_user_id\"");
                        });
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.PendingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("pending_matches", t =>
                        {
                            t.HasCheckConstraint("ck_pending_no_self", "\"user_id\" <> \"target_user_id\"");
                        });
                });

            modelBuilder.Entity("MatchOutcome", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.Data.AuthIdentity", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.DailyDeck", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.MatchExplanation", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserDynamicIntakeSet", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserFoundationalQuestionSet", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserVector", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.Entities.UserVectorTag", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserFoundationalV1", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithOne()
                        .HasForeignKey("WovenBackend.Data.UserFoundationalV1", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserIntent", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithOne()
                        .HasForeignKey("WovenBackend.Data.UserIntent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserOptionalField", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserPhoto", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserPreference", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithOne()
                        .HasForeignKey("WovenBackend.Data.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserProfile", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithOne()
                        .HasForeignKey("WovenBackend.Data.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.Data.UserWeeklyVibe", b =>
                {
                    b.HasOne("WovenBackend.Data.User", "User")
                        .WithOne()
                        .HasForeignKey("WovenBackend.Data.UserWeeklyVibe", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.Block", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.ChatMessage", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WovenBackend.data.Entities.Moments.ChatThread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.ChatThread", b =>
                {
                    b.HasOne("WovenBackend.data.Entities.Moments.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.DailyInteraction", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.Match", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("EdgeOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.MomentResponse", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WovenBackend.data.Entities.Moments.PendingMatch", b =>
                {
                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WovenBackend.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
